# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
# Wax-Kit uses Jekyll-style configuraton files.

title:            'Paper Databases'
description:      'Data on paper'
url:              'https://paperdata.benschmidt.org/'
baseurl:          '/'
copyright:        'copyright 2021'
logo:             '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

theme: wax_theme
permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false

minify_html: false
# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  19C: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'generic_collection_item' # the layout for the pages to use
    metadata:
      source: 'bigdata1.csv' # path to the metadata file within `_data`
      # The thing after the slash is the individual sheet.
      google_drive_id: '1dAIKPxhCmqgz3r9h21_muJolEVGzRYIN7Syg1_js6qI'
    images:
      source: 'raw_images/images' # path to the directory of images within `_data`
      google_drive_ids:
        - '1xG-qqCFYGT6plpnGOKYL_qR_blf_Ctry'
# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      nara:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - a_number
          - name

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    sub:
      - label: 'Wax'
        link: '/about/'
      - label: 'Credits'
        link: '/credits/'
  - label: 'Exhibits'
    sub:
      - label: "Lomax"
        link: '/exhibits/lomax'
        google_drive_id: 1IH8I6B5Yi0JBpA7q5vjMhnCFUmisYWV3h12o_bF03kA
      - label: "YMCA Punch Cards"
        link: '/exhibits/ymca'
        google_drive_id: 1NDRm_qLqAFONg0moVl8V3SPB-X4WcF9kzIwXUdh-Kr4
      - label: "Baseball Scorecards"
        link: '/exhibits/baseball'
        google_drive_id: 1yx2RDiiM_6fB_AXwmb__bnrSnkzfejP9vH82bo8O1xk
      - label: Marriage Certificate
        link: '/exhibits/marriage'
        google_drive_id: 1LhqYXvkpY6y5eXlfLKRpHOAAFPBZhG_Bb4gRXaMEhF8
      - label: Military payments
        link: '/exhibits/manifest'
        google_drive_id: '15-mABLINXzCaJLR1aEdfrVJf1_xLl-pJXRjRsI_PBhk'
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'
  - label: 'Reuse'
    link: '/reuse/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------


footer:
  links:
#    - label: 'GitHub'
#      link: 'https://github.com/minicomp/wax'
#    - label: 'Credits'
#      link: '/credits'
#    - label: 'Contact'
#      link: 'https://gitter.im/minicomp/wax/'
  logos:
    - img: '/img/logo.png'

# FIN
