# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
# Wax-Kit uses Jekyll-style configuraton files.

title:            'Paper Databases'
description:      'Data on paper'
url:              'https://paperdata.benschmidt.org/'
baseurl:          '/'
copyright:        'copyright 2021'
logo:             '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

theme: wax_theme
permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false

minify_html: false
# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  datasets: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'generic_collection_item' # the layout for the pages to use
    metadata:
      source: 'bigdata1.csv' # path to the metadata file within `_data`
      # The thing after the slash is the individual sheet.
      google_drive_id: '1dAIKPxhCmqgz3r9h21_muJolEVGzRYIN7Syg1_js6qI'
    images:
      source: 'raw_images/images' # path to the directory of images within `_data`
      google_drive_ids:
        - '1xG-qqCFYGT6plpnGOKYL_qR_blf_Ctry'
  appendix:
    output: true
    metadata:
      source: 'bigdata2.csv'
      google_drive_id: '1m8VFI8qQ-AOL0sXcTnE2aTUlCspaKQbbGZbn6sHTHY0'
    images:
      source: 'raw_images/images'
      google_drive_ids:
        - '1xG-qqCFYGT6plpnGOKYL_qR_blf_Ctry'
# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      nara:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - a_number
          - name

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    sub:
      - label: 'Wax'
        link: '/about/'
      - label: 'Credits'
        link: '/credits/'
  - label: 'Exhibits'
    sub: [
      {
        "title": "Demonstration Essay",
        "author_for_public_display": "Professor Schmidt",
        "google_drive_id": "1FTt5zCVWuX3Pmm_nnRgijv-N3AGqZa_vMwwMIzgG72Y",
        "site_link": "/exhibits/demo",
        "sentence_summary": "A demonstration for students of how this works.",
        "demo_image_id": "datasets/bell_aircraft_complaint_page_01"
      },
      {
        "title": "Lomax",
        "author_for_public_display": "",
        "google_drive_id": "1IH8I6B5Yi0JBpA7q5vjMhnCFUmisYWV3h12o_bF03kA",
        "site_link": "/exhibits/lomax",
        "sentence_summary": "",
        "demo_image_id": ""
      },
      {
        "title": "YMCA Punch Cards",
        "author_for_public_display": "",
        "google_drive_id": "1NDRm_qLqAFONg0moVl8V3SPB-X4WcF9kzIwXUdh-Kr4",
        "site_link": "/exhibits/ymca",
        "sentence_summary": "",
        "demo_image_id": ""
      },
      {
        "title": "Baseball Scorecards",
        "author_for_public_display": "",
        "google_drive_id": "1yx2RDiiM_6fB_AXwmb__bnrSnkzfejP9vH82bo8O1xk",
        "site_link": "/exhibits/baseball-2",
        "sentence_summary": "",
        "demo_image_id": ""
      },
      {
        "title": "Marriage Certificate",
        "author_for_public_display": "",
        "google_drive_id": "1LhqYXvkpY6y5eXlfLKRpHOAAFPBZhG_Bb4gRXaMEhF8",
        "site_link": "/exhibits/marriage",
        "sentence_summary": "",
        "demo_image_id": ""
      },
      {
        "title": "Operation Neptune Manifest",
        "author_for_public_display": "Milo Servin",
        "google_drive_id": "15-mABLINXzCaJLR1aEdfrVJf1_xLl-pJXRjRsI_PBhk",
        "site_link": "/exhibits/manifest",
        "sentence_summary": "The development of more advanced data management systems analyzed through a WW2 Jump Manifest.",
        "demo_image_id": "datasets/es5045_d-day-jump-manifest-document"
      },
      {
        "title": "Prison Labor records",
        "author_for_public_display": "",
        "google_drive_id": "1D_NW525nyMUiD57pcSaoK0jmK8elb31bgvOFX0WgSxQ",
        "site_link": "/exhibits/prison",
        "sentence_summary": "",
        "demo_image_id": ""
      },
      {
        "title": "Banks and Steamships",
        "author_for_public_display": "Prajjwal Bhattarai",
        "google_drive_id": "1YTVZxPNfw9msleuSSkQixGiFE4VLPiC10jP-quy-YrA",
        "site_link": "/exhibits/steamships",
        "sentence_summary": "The unique position of immigrant banks in early twentieth century immigrant communities reflected through steamship ticket purchase ledgers",
        "demo_image_id": "datasets/prajjwal_steamship"
      },
      {
        "title": "USS Vermont Logs",
        "author_for_public_display": "Matthew Kaufman",
        "google_drive_id": "17w_Q7eJCZcdzncV3SJ3U_ft-2OKAuyRYjok8BDcYMXI",
        "site_link": "/exhibits/vermont",
        "sentence_summary": "An analysis of Naval logs from the USS Vermont",
        "demo_image_id": ""
      },
      {
        "title": "Carnegie Hall Ledgers",
        "author_for_public_display": "",
        "google_drive_id": "17wPdvIwB-n1O0eAo8WzxWv9_9mHaobA2RY5RrVpB9AQ",
        "site_link": "/exhibits/carnegie-hall",
        "sentence_summary": "Exploring coordination of information gathering and efficacy of collecting information on paper through Carnegie Hall's booking ledgers.",
        "demo_image_id": "datasets/carnegiehallbookingledger1955"
      },
      {
        "title": "James Madison's Meteorological Journal",
        "author_for_public_display": "",
        "google_drive_id": "1-5kBAOl8kaWHY-lQgjZsBX4Bmn_BPwbtVHLjmLUSlqo",
        "site_link": "/exhibits/madison",
        "sentence_summary": "How the current digitization process leads to crucial historical information being lost",
        "demo_image_id": "datasets/Madison Weather Journal Page"
      },
      {
        "title": "Cavalry Medical Records",
        "author_for_public_display": "Daija Dewberry",
        "google_drive_id": "1Fv6dz3qwTaTcSYMFDTRmJl3oueewDW8kclPXu4S7UhA",
        "site_link": "/exhibits/cavalry-medical",
        "sentence_summary": "The effects of digitization on a database examined through the U.S. government's early efforts in database creation.",
        "demo_image_id": ""
      },
      {
        "title": "Tribal Census Registers",
        "author_for_public_display": "",
        "google_drive_id": "10TZCxiZVFQdeEyHwvhjbaopkZ6mSON_CEVBKyMCYriA",
        "site_link": "/exhibits/tribal-census",
        "sentence_summary": "",
        "demo_image_id": ""
      },
      {
        "title": "Baseball Scorecards",
        "author_for_public_display": "Jaz Quaranta",
        "google_drive_id": "17wblCoADDmZ4wkD6MBY0OhB02g4U4w8NYuAQQbkta-0",
        "site_link": "/exhibits/scorecards",
        "sentence_summary": "An examination of a timeline of a set of baseball scorecards, and how their rule changes allow for a better understanding of the episteme",
        "demo_image_id": ""
      },
      {
        "title": "Draft cards",
        "author_for_public_display": "",
        "google_drive_id": "1zL3skFCSNMHMstjphTchHxK7T5tn0Qiov7YYINShGRo",
        "site_link": "/exhibits/draft-cards",
        "sentence_summary": "",
        "demo_image_id": ""
      },
      {
        "title": "Navy Logs",
        "author_for_public_display": "",
        "google_drive_id": "103iaxwowJ6vSu3ECcYjF0YhAyLYNA3qo-n2Ek-5_AIk",
        "site_link": "/exhibits/navy",
        "sentence_summary": "A collection of deck logs from US Navy ships during WWII",
        "demo_image_id": ""
      },
      {
        "title": "NY Philharmonic Attendance",
        "author_for_public_display": "",
        "google_drive_id": "1cNhrLoK8DErsshmupAUFJut3WT9_TYcX3igGcwl2SaU",
        "site_link": "/exhibits/philharmonic",
        "sentence_summary": "",
        "demo_image_id": ""
      }
    ]
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'
  - label: 'Reuse'
    link: '/reuse/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------


footer:
  links:
#    - label: 'GitHub'
#      link: 'https://github.com/minicomp/wax'
#    - label: 'Credits'
#      link: '/credits'
#    - label: 'Contact'
#      link: 'https://gitter.im/minicomp/wax/'
  logos:
    - img: '/img/logo.png'

# FIN
